[debug] Running TaskDef(pvu.PvuTopTest, org.scalatest.tools.Framework$$anon$1@f360808, false, [SuiteSelector])
[info] PvuTopTest:
[info] PvuTop
[info] - should correctly convert posit numbers between different precisions *** FAILED ***
[info]   In step 1: io_posit_o_0=0 (0x0) did not equal expected=32768 (0x8000) at (PvuTopTest.scala:34) (PvuTopTest.scala:34)
[info] - should handle invalid inputs correctly *** FAILED ***
[info]   In step 2: io_posit_o_0=2147483648 (0x80000000) did not equal expected=65535 (0xffff) at (PvuTopTest.scala:110) (PvuTopTest.scala:110)
[info] - should handle different ES values correctly *** FAILED ***
[info]   In step 1: io_posit_o_0=0 (0x0) did not equal expected=32768 (0x8000) at (PvuTopTest.scala:133) (PvuTopTest.scala:133)
[info] - should correctly compare posit numbers and output the greater value *** FAILED ***
[info]   chisel3.package$ChiselException: Value 8 does not fit into the range of PvuTop.io.op: IO[UInt<3>] (0 ... 7)
[info]   at chiseltest.package$Utils$.ensureInRange(package.scala:322)
[info]   at chiseltest.package$Utils$.ensureFits(package.scala:303)
[info]   at chiseltest.package$testableUInt.poke(package.scala:67)
[info]   at chiseltest.package$testableUInt.poke(package.scala:65)
[info]   at pvu.PvuTopTest.$anonfun$new$12(PvuTopTest.scala:142)
[info]   at pvu.PvuTopTest.$anonfun$new$12$adapted(PvuTopTest.scala:140)
[info]   at chiseltest.internal.SimController.run(SimController.scala:124)
[info]   at chiseltest.internal.Context$.$anonfun$runTest$2(Context.scala:30)
[info]   at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
[info]   at chiseltest.internal.Context$.runTest(Context.scala:30)
[info]   ...
[info] Run completed in 16 minutes, 3 seconds.
[info] Total number of tests run: 4
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 0, failed 4, canceled 0, ignored 0, pending 0
[info] *** 4 TESTS FAILED ***
[error] Failed tests:
[error] 	pvu.PvuTopTest
[error] (Test / testOnly) sbt.TestsFailedException: Tests unsuccessful
